[package]
name = "neddit-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ammonia = "4.1.4"
askama = "0.16.1"
askama_web = { version = "0.16.0", features = ["axum-0.8", "tracing-0.1"] }
axum.workspace = true
neddit-api.workspace = true
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
tower-http.workspace = true
tower-livereload = "0.10.3"
url.workspace = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
