#!/bin/sh
set -eu

exec cargo watch \
  --watch crates/neddit \
  --watch crates/web \
  --watch crates/api \
  --watch Cargo.toml \
  --watch Cargo.lock \
  --exec 'run -p neddit --locked -- --config "$PWD/config.toml"'
