[package]
name = "neddit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
clap = { version = "4.4.11", default-features = false, features = [
	"std",
	"env",
	"derive",
	"error-context",
	"help",
	"usage",
] }
neddit-api.workspace = true
neddit-web = { path = "../web" }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml = { version = "0.9.8", default-features = false, features = ["parse", "serde"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt", "json"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
